vich_uploader:
    db_driver: orm
    mappings:
        post_images:
            uri_prefix: '/~22_sagan/todo-app/uploads/posts'
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true